development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: music_app_development
  pool: 5
  username: root
  password: shmuvele
  host: localhost

test:
  adapter: mysql2
  database: music_app_test
  pool: 5
  username: root
  password: shmuvele
  host: localhost
  timeout: 5000